[general]
live_config_reload = true
import = ["~/.config/alacritty/dracula.toml"]

[env]

[window]
opacity = 0.9

[scrolling]
history = 10000
multiplier = 30

[font]
size = 16.0

[font.normal]
family = "Moralerspace Neon HW"
style = "Regular"

[font.bold]
family = "Moralerspace Neon HW"
style = "Bold"

[colors]
draw_bold_text_with_bright_colors = true

[bell]

[selection]

[cursor]

[terminal]

[mouse]

[hints]

[keyboard]

[debug]
